# Generated by Django 3.0.4 on 2020-04-13 04:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('insta', '0002_auto_20200412_0725'),
    ]

    operations = [
        migrations.AlterField(
            model_name='instauser',
            name='profilepic',
            field=models.ImageField(default='', upload_to='profile_pic'),
        ),
        migrations.AlterField(
            model_name='photo',
            name='likes',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
