# Generated by Django 3.0.4 on 2020-04-14 10:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('insta', '0006_follower'),
    ]

    operations = [
        migrations.AddField(
            model_name='photo',
            name='owner_profilepic',
            field=models.CharField(default='', max_length=256),
        ),
    ]
