# Generated by Django 3.0.4 on 2020-04-15 12:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('insta', '0008_auto_20200414_1627'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comments',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('postid', models.IntegerField()),
                ('comment', models.CharField(max_length=500)),
                ('commenter', models.CharField(max_length=256)),
            ],
        ),
        migrations.CreateModel(
            name='Likes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('postid', models.IntegerField()),
                ('liker', models.CharField(max_length=256)),
            ],
        ),
        migrations.AddField(
            model_name='photo',
            name='comments',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
